/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ADivider: typeof import('ant-design-vue/es')['Divider']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Scroll: typeof import('./src/components/scroll.vue')['default']
  }
}
